### PR TITLE
Corrected Predix UI display

### PR DESCRIPTION
**Pull request by thierryfa**
* ## A description of the changes proposed in the pull request:

Last Friday, I regenerated the bower_compents directory of a prototype project I am developing and then the UI was displayed in grey levels instead of standard Predix UI blue levels. I found out that px-theme went from 3.1.0 to 3.1.3 in the process.

I have done all what is needed to get the Predix theme (with `<link rel="import" href="/bower_components/px-theme/px-theme-styles.html"/>` and `<style include="px-theme-styles">` in the code) and I suspect a regression in this component related to the CSS rule on `html` element that should also be applied on `:host>*` elements, This was done like this in version 3.1.0.

So, here is a new version that corrects the problem, at least in my case.

* ## working tests:

I don't have a test. Here are the screen shots of my application before and after correction:

before
after

### CODE REVIEW

**Comment by mdwragg** [comment]
Hi, what version of Polymer are you using?

**Comment by mdwragg** [comment]
The previous selector was invalid in edge and IE, hence the change. I followed this for inspiration: https://www.polymer-project.org/2.0/start/first-element/step-5 (theming at document level)

**Comment by thierryfa** [comment]
Thanks for the link. I'm using polymer 2 and I understand now that the syntax has changed and that I have to embed the `<style>` element inside a `<custom-style>` element instead of using the `is` attribute.

I'm on mobile right now and I will be able to test it only tomorrow. But I am confident that it will work.

Maybe Predix UI documentation could be updated to describe the alternative syntax for polymer 2.

**Comment by mdwragg** [comment]
Hi, cool, that is good news. We’re working on our Polymer 2.x/hybrid element migration now. We’ll refine docs when the time is right - for our Polymer 1.x customers nothing should change though.

Once you’ve retested and are happy things work, please don’t forget to close he PRs/defects. Thanks!

**Comment by thierryfa** [comment]
It can be closed. The problem was that in Polymer 2, the syntax to get the standard Predix UI blue levels is to embed the px-theme style in a custom-style element. This has to be done once in the root index.html:

```html
    <link rel="import" href="/bower_components/px-theme/px-theme-styles.html">
    <custom-style>
        <style include="px-theme-styles"></style>
    </custom-style>
```

I understand that the components themselves don't need to refer to px-theme styles sheet again. The philosophy is that the global theme is defined once for all in an application.

**Pull request closed without merging**
